name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'pnpm'
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run Playwright tests
        run: |
          docker run --rm \
            --name playwright \
            --network host \
            -e CI=true \
            -e PLAYWRIGHT_BROWSERS_PATH=/usr/bin \
            -v /dev/shm:/dev/shm \
            -v $(pwd):/src \
            -w /src/packages/admin \
            mcr.microsoft.com/playwright:focal \
            pnpm e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/admin/playwright-report/
          retention-days: 30
