name: Playwright Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run Playwright tests
        run: cd packages/admin && pnpm e2e
        env:
          HOME: '/root'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/admin/playwright-report/
          retention-days: 30
